version: '3.8'
services:
  
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web
  
  web:
    image: maratagliullin/foodgram:v1
    restart: always
    volumes:
      - ../backend/foodgram:/app
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    command: bash run_management_commands.sh

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

  db:
    image: postgres:13.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env  

volumes:
  static_value:
  media_value:
  pgdata:
 