# Generated by Django 4.1 on 2022-09-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Идиница измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='foods.measurementunits', verbose_name='Единица изменения'),
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
