# Generated by Django 4.1 on 2022-09-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_measurementunits_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementunits',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.PositiveSmallIntegerField(help_text='Время приготовления в минутах', verbose_name='Время приготовления'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'recipe_ingredients', 'amount'), name='unique_recipe_recipe_ingredients_amount'),
        ),
    ]
