# Generated by Django 4.1 on 2022-09-08 11:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0007_alter_measurementunits_options_alter_recipe_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritedRecipesByUsers',
            new_name='FavoritedRecipesByUser',
        ),
        migrations.RenameModel(
            old_name='MeasurementUnits',
            new_name='MeasurementUnit',
        ),
    ]
