# Generated by Django 4.1 on 2022-09-08 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0008_rename_favoritedrecipesbyusers_favoritedrecipesbyuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritedRecipesByUser',
            new_name='FavoritedRecipeByUser',
        ),
    ]
