# Generated by Django 4.1 on 2022-09-05 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribersByCurrentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Текущий пользователь')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL, verbose_name='Подписан')),
            ],
            options={
                'verbose_name': 'Подписчики',
                'verbose_name_plural': 'Подписчики',
                'unique_together': {('current_user', 'subscription')},
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='user_to_shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Текущий пользователь')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='foods.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Список покупок',
                'unique_together': {('current_user', 'recipe')},
            },
        ),
        migrations.CreateModel(
            name='FavoritedRecipesByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='user_to_favorited', to=settings.AUTH_USER_MODEL, verbose_name='Текущий пользователь')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='foods.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Список избранного',
                'verbose_name_plural': 'Список избранного',
                'unique_together': {('current_user', 'recipe')},
            },
        ),
    ]
