# Generated by Django 4.1 on 2022-09-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_favoritedrecipesbyuser_favoritedrecipesbyusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritedRecipesByUsers',
        ),
    ]
