# Generated by Django 4.1 on 2022-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_favoritedrecipesbyusers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcartbyuser',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subscribersbycurrentuser',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartbyuser',
            constraint=models.UniqueConstraint(fields=('current_user', 'recipe'), name='unique_current_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='subscribersbycurrentuser',
            constraint=models.UniqueConstraint(fields=('current_user', 'subscription'), name='unique_current_current_user_subscription'),
        ),
    ]
